export const MOTIVATIONAL_PHRASES: string[] = [
  'Hoy puede ser el comienzo de algo maravilloso.',
  'Hay más fuerza en ti de la que imaginas.',
  'Cada día trae una nueva oportunidad para avanzar.',
  'Lo que sueñas puede tomar forma si sigues intentándolo.',
  'Incluso un paso pequeño puede llevarte más lejos de lo que crees.',
  'Tu historia puede renovarse en cualquier momento.',
  'La luz siempre encuentra la manera de entrar.',
  'La vida puede sorprenderte de formas que aún no imaginas.',
  'Tu capacidad de crecer no tiene límites fijos.',
  'Lo mejor puede estar justo por delante.',
  'Confía: hay caminos que se revelan al caminar.',
  'Tu esfuerzo puede abrir puertas inesperadas.',
  'Cada amanecer trae nuevas posibilidades.',
  'Si miras al frente, es más fácil avanzar.',
  'Hoy puede ser el día en que algo cambie para bien.',
  'Tu constancia puede transformar lo ordinario en extraordinario.',
  'Siempre hay motivos para creer en lo que viene.',
  'La energía para comenzar está más cerca de lo que piensas.',
  'Atrévete a imaginar algo más grande para ti.',
  'Lo que hoy comienza puede traer grandes alegrías mañana.',
  'Dentro de ti hay más potencial del que has descubierto.',
  'Cada intento suma; nada se pierde.',
  'Confía en que puedes lograr lo que te propones.',
  'Tus decisiones tienen poder.',
  'Hay espacio para crecer incluso en los días tranquilos.',
  'La esperanza puede levantarte cuando menos lo esperas.',
  'Puedes iluminar tu camino con tus propias ideas.',
  'Siempre hay una oportunidad esperando ser tomada.',
  'Tu ánimo puede encender nuevas posibilidades.',
  'Lo que construyes hoy puede sostenerte mañana.',
  'Tienes todo para hacer de este año algo inolvidable.',
  'La amistad auténtica acompaña sin condición.',
  'Un vínculo sincero siembra luz en el camino.',
  'La compañía amable hace más ligera cualquier jornada.',
  'Una palabra amiga puede traer claridad.',
  'La confianza compartida fortalece el corazón.',
  'La amistad crece cuando se honra con presencia.',
  'Un gesto cercano puede unir historias distintas.',
  'La escucha amiga revela caminos nuevos.',
  'La amistad verdadera celebra tu esencia.',
  'Cada encuentro sincero deja huellas profundas.',
  'La presencia amiga ofrece calor en cualquier día.',
  'La alegría compartida se multiplica sin medida.',
  'Una conversación honesta puede renovar el ánimo.',
  'La amistad cuida sin pedir nada a cambio.',
  'Un abrazo imaginado también es compañía.',
  'La lealtad silenciosa sostiene incluso en la distancia.',
  'Cada amistad es una puerta abierta al aprendizaje.',
  'El apoyo amable hace más claro el horizonte.',
  'Una mirada amistosa puede despertar esperanza.',
  'La amistad genuina reconoce el valor de cada paso.',
  'Caminar junto a alguien vuelve el viaje significativo.',
  'La amistad abraza sin juzgar.',
  'Un recuerdo compartido guarda calor en el alma.',
  'La amistad invita a descubrir nuevas posibilidades.',
  'Una mano tendida puede transformar un día.',
  'La amistad agradecida fortalece los lazos.',
  'Estar en compañía hace más suave el trayecto.',
  'La amistad sincera inspira caminos de paz.',
  'Un corazón amigo siempre encuentra maneras de acompañar.',
  'La calma florece cuando te abres al momento.',
  'La serenidad se siente como viento tibio al amanecer.',
  'Cada brote nuevo recuerda que siempre hay comienzo.',
  'La paz se asienta cuando respiras con suavidad.',
  'Al observar la naturaleza, algo adentro se ordena.',
  'La naturaleza recuerda el valor de avanzar sin prisa.',
  'Los días claros traen luz para seguir creciendo.',
  'Una brisa ligera también puede traer alivio.',
  'La quietud del cielo invita a mirar hacia dentro.',
  'Cada pétalo abierto celebra la vida.',
  'La serenidad nace cuando sueltas la urgencia.',
  'Un rayo de sol puede renovar tu ánimo.',
  'Los colores nuevos anuncian esperanza.',
  'Cuando la tierra despierta, el corazón también.',
  'La paz interior se siente como un jardín cuidado.',
  'Un sendero verde invita a caminar con calma.',
  'Un amanecer luminoso limpia pensamientos.',
  'Donde hay luz, la tranquilidad encuentra espacio.',
  'La naturaleza recuerda que todo tiene su tiempo.',
  'Los ciclos naturales inspiran paciencia.',
  'La serenidad aparece al observar sin prisa.',
  'Un paisaje tranquilo ayuda a encontrar claridad.',
  'Imaginar el canto de las aves trae sencillez al día.',
  'Cada amanecer temprano ofrece silencio amable.',
  'La vida se renueva también en lo pequeño.',
  'El aire fresco invita a abrir el corazón.',
  'Un árbol firme enseña a permanecer en calma.',
  'La luz matutina enciende nueva confianza.',
  'La naturaleza entera acompaña tus procesos.',
  'Una pausa bajo el sol reconforta el espíritu.',
  'La paz florece cuando decides recibir la vida tal como llega.',
  'Cada día puede recordarte que hay cosas buenas cerca.',
  'La vida puede sentirse más plena cuando aprecias lo que tienes.',
  'Valorar lo que te rodea puede abrirte a nuevas alegrías.',
  'A veces, reconocer lo sencillo trae claridad.',
  'Lo cotidiano puede guardar tesoros que vale la pena mirar.',
  'Agradecer lo que hay puede encender más luz a tu alrededor.',
  'Si observas con calma, puedes encontrar motivos para sonreír.',
  'Cada momento puede ofrecer algo digno de celebrarse.',
  'La vida puede sentirse más ligera cuando notas lo que sí está.',
  'Reconocer lo presente puede inspirar nuevas ideas.',
  'Siempre hay algo valioso esperando ser visto.',
  'Un pensamiento agradecido puede transformar tu día.',
  'Honrar lo que ya existe puede fortalecer tu camino.',
  'Valorar cada paso puede darle sentido a tu recorrido.',
  'La belleza puede estar más cerca de lo que imaginas.',
  'Cuando aprecias lo simple, crece el bienestar.',
  'La vida puede sorprenderte cuando miras con atención.',
  'Notar lo que sí funciona puede darte impulso.',
  'Cada experiencia guarda algo que puede servirte.',
  'Valorar lo vivido puede abrirte a lo que viene.',
  'Tu entorno puede ofrecerte más de lo que parece.',
  'Honrar lo que tienes puede ayudarte a avanzar.',
  'Saber encontrar algo bueno en tu día puede darte energía nueva.',
  'Reconocer lo positivo puede traer claridad.',
  'Valorar tu camino puede fortalecer tu confianza.',
  'Cada mañana puede brindar algo que admirar.',
  'Lo que aprecias puede crecer contigo.',
  'Si observas con calma, puedes encontrar motivos para sonreír.',
  'Cuando agradeces, tu mundo se expande.',
  'Aceptar y valorar lo presente puede abrirte nuevas puertas.',
  'Prestar atención sincera puede acercarte a quienes te rodean.',
  'Comprender a alguien puede acercarte a su mundo.',
  'Un gesto amable puede iluminar más de lo que imaginas.',
  'Mirar con respeto puede crear puentes duraderos.',
  'La conexión puede crecer cuando te abres a entender.',
  'Cada vínculo puede fortalecerse con una escucha sincera.',
  'Una palabra cálida puede transformar un momento.',
  'Ver con el corazón puede revelar nuevas historias.',
  'La empatía puede traer calma a cualquier encuentro.',
  'La comprensión puede nacer de una mirada atenta.',
  'Aceptar a alguien tal como es puede acercar caminos.',
  'La presencia puede ser el regalo más valioso.',
  'Un gesto amable puede suavizar el camino.',
  'Acompañar en silencio también es compartir.',
  'Comprender sin juzgar puede abrir horizontes.',
  'Un pequeño acto de cuidado puede dejar huella.',
  'La apertura puede acercarte a otras realidades.',
  'Notar lo que alguien siente puede unir caminos.',
  'La compasión puede suavizar los días difíciles.',
  'Una sonrisa puede tender puentes invisibles.',
  'Cada persona guarda una historia digna de escucharse.',
  'La amabilidad puede llegar más lejos de lo esperado.',
  'Mirar con empatía puede traer claridad al corazón.',
  'El respeto puede contener más fuerza de la que parece.',
  'Estar disponible puede ser suficiente.',
  'Aceptar las diferencias puede enriquecer tu camino.',
  'La ternura puede fortalecer los vínculos.',
  'Entender a alguien puede inspirarte a crecer.',
  'Una escucha atenta puede transformar una conversación.',
  'La cercanía puede construirse paso a paso.',
  'Cada encuentro puede dejar una enseñanza sutil.',
  'Compartir algo propio puede abrir caminos nuevos.',
  'Un gesto amable puede transformar un día.',
  'Brindar apoyo puede crear puentes valiosos.',
  'Ofrecer tiempo puede ser un regalo inmenso.',
  'Sembrar algo bueno puede tocar muchos corazones.',
  'Dar sin esperar puede enriquecer cualquier encuentro.',
  'Tender la mano puede acercar historias distintas.',
  'Ofrecer escucha puede cambiar la dirección de una conversación.',
  'Compartir experiencias puede inspirar a quienes te rodean.',
  'Aportar lo mejor de ti puede iluminar tu entorno.',
  'Un acto desinteresado puede sembrar esperanza.',
  'Abrir espacio a otras voces puede fortalecer vínculos.',
  'Regalar tu presencia puede ser suficiente.',
  'Dar oportunidad a alguien puede abrir horizontes.',
  'Compartir palabras cálidas puede traer alivio.',
  'Ofrecer comprensión puede sostener a quien lo necesita.',
  'Dar acompañamiento puede hacer el camino más amable.',
  'Un detalle sencillo puede dejar huella.',
  'Brindar cariño puede despertar alegría.',
  'Compartir aprendizajes puede impulsar a otras personas.',
  'Estar disponible puede ser un acto profundo.',
  'Dar atención puede nutrir un vínculo.',
  'Ofrecer apoyo puede traer calma a tu alrededor.',
  'Compartir talentos puede multiplicar posibilidades.',
  'Una invitación amable puede abrir nuevas puertas.',
  'Regalar palabras sinceras puede fortalecer el alma.',
  'Aportar tu energía puede animar a quien te acompaña.',
  'Compartir camino puede dar sentido a la travesía.',
  'Ofrecer tu mejor intención puede generar luz.',
  'Dar desde el corazón puede engrandecer tu vida.',
  'Agradecer cada momento abre espacio para la serenidad.',
  'Valorar lo que ya existe da fuerza al presente.',
  'Reconocer los pequeños gestos enriquece el camino.',
  'Honrar lo vivido trae nueva claridad.',
  'Apreciar lo que llega invita a seguir creciendo.',
  'La gratitud hace más luminoso lo cotidiano.',
  'Reconocer la ayuda recibida fortalece los lazos.',
  'Valorar la propia historia da sentido al andar.',
  'Agradecer lo aprendido impulsa nuevos pasos.',
  'Encontrar belleza en lo simple anima el corazón.',
  'Honrar a quienes acompañan crea vínculos firmes.',
  'Apreciar cada amanecer inspira esperanza.',
  'Reconocer lo valioso despierta gratitud interior.',
  'Agradecer la compañía genera cercanía.',
  'Valorar cada avance mantiene el ánimo despierto.',
  'Agradecer los instantes de calma nutre el espíritu.',
  'Apreciar lo presente invita a mirar con mayor suavidad.',
  'Reconocer lo esencial afina la mirada.',
  'Honrar lo recibido acerca a la plenitud.',
  'Agradecer pensamientos amables enciende alegría.',
  'Valorar los encuentros suma luz al día.',
  'Agradecer lo que permanece fortalece la confianza.',
  'Apreciar los detalles despierta sensibilidad.',
  'Reconocer los frutos logrados anima a seguir.',
  'Agradecer el camino recorrido brinda paz interior.',
  'Valorar las palabras sinceras crea conexión auténtica.',
  'Apreciar cada gesto amable abre nuevas puertas.',
  'Honrar las raíces sostiene el crecimiento.',
  'Reconocer aquello que suma aclara el horizonte.',
  'Agradecer el presente enriquece la vida.',
  'Valorar la historia personal prepara para lo nuevo.',
  'La aceptación abre caminos donde antes había resistencia.',
  'Al abrazar tu historia, surge una paz más profunda.',
  'Lo que es también tiene algo que enseñarte.',
  'Cuando miras con apertura, aparece un nuevo entendimiento.',
  'En la aceptación nace una libertad suave.',
  'Cada parte de tu camino merece un lugar en tu corazón.',
  'Aceptar el momento presente fortalece el espíritu.',
  'La calma florece cuando dejas de luchar con lo inevitable.',
  'La vida se siente más ligera cuando das espacio a lo que ocurre.',
  'Al soltar la exigencia, aparece la claridad.',
  'Aceptar tu ritmo honra tu proceso.',
  'Lo que hoy vives también es parte de tu crecimiento.',
  'Una mirada comprensiva suaviza cualquier paso.',
  'La aceptación transforma lo difícil en aprendizaje.',
  'La serenidad llega cuando escuchas sin juicio.',
  'Cada experiencia encuentra su lugar cuando la recibes sin prisa.',
  'En la apertura hay fuerza silenciosa.',
  'Aceptar lo que cambia permite avanzar.',
  'Incluso lo inesperado puede traer sabiduría.',
  'La aceptación convierte la rigidez en flexibilidad interior.',
  'Lo que reconoces con aceptación se vuelve más liviano.',
  'Al permitir que las cosas sean, aparece un nuevo orden.',
  'La comprensión a tiempo abre puertas internas.',
  'Nada se pierde cuando aceptas y sigues avanzando.',
  'La aceptación brinda descanso al corazón.',
  'Cada paso tiene sentido cuando se acoge con presencia.',
  'Escuchar tu verdad interior invita a la calma.',
  'Aceptar lo que sientes te acerca a lo real.',
  'En la bienvenida a cada momento surge la sabiduría.',
  'Cuando abrazas lo que llega, florecen nuevas posibilidades.',
  'La aceptación del presente fortalece el mañana.',
  'La alegría nace muchas veces en los detalles simples.',
  'Un momento ligero puede iluminar toda la jornada.',
  'La risa sincera abre espacio al bienestar.',
  'A veces, la alegría aparece sin anunciarse.',
  'Dejar entrar lo amable hace el camino más luminoso.',
  'Un recuerdo feliz puede dar fuerza al presente.',
  'La luz interior encuentra formas de mostrarse.',
  'Cada día guarda instantes llenos de brillo.',
  'La alegría también vive en el silencio.',
  'Celebrar lo pequeño hace grande el corazón.',
  'La sorpresa de un buen momento cambia la energía del día.',
  'Una sonrisa sincera invita a seguir avanzando.',
  'La alegría puede brotar en lugares inesperados.',
  'Encontrar color en lo cotidiano anima el espíritu.',
  'La sonrisa es un puente hacia la esperanza.',
  'La vida se vuelve más bella cuando honras lo agradable.',
  'Una mirada amable despierta entusiasmo.',
  'Dejar florecer la alegría es también un acto de amor.',
  'Un instante luminoso renueva el ánimo.',
  'La alegría compartida multiplica su fuerza.',
  'La sorpresa amable refresca el corazón.',
  'Cada rayo de alegría renueva la mirada.',
  'Un pensamiento ligero da alas a la imaginación.',
  'La alegría suaviza cualquier paso.',
  'Un rostro sonriente puede tocar una vida.',
  'La vida brilla cuando te abres a sus colores.',
  'Una emoción alegre despierta nuevas posibilidades.',
  'Un instante de gozo puede encender tu jornada.',
  'La alegría también acompaña los días tranquilos.',
  'Cada amanecer trae una invitación a sonreír.',
  'La creatividad se despierta cuando das espacio a tus ideas.',
  'Un pensamiento curioso puede abrir caminos nuevos.',
  'La inspiración llega cuando escuchas lo que surge dentro.',
  'Mirar desde otro ángulo enciende la imaginación.',
  'Cada día trae una fulgor listo para encender algo nuevo.',
  'Lo que imaginas puede convertirse en una creación valiosa.',
  'Un pequeño impulso creativo puede transformar tu rumbo.',
  'La mente abierta encuentra oportunidades inesperadas.',
  'Una idea sencilla puede tener gran significado.',
  'Colores nuevos aparecen cuando exploras otras rutas.',
  'La curiosidad guía pasos llenos de hallazgos.',
  'Cada pensamiento libre invita a jugar con lo posible.',
  'Un momento de silencio puede revelar inspiración.',
  'La creatividad florece cuando no te apresuras.',
  'Nuevas formas nacen cuando te permites experimentar.',
  'La imaginación es un puente hacia realidades nuevas.',
  'Un destello interior puede iluminar todo un camino.',
  'Nada es pequeño cuando se crea con intención.',
  'La creatividad encuentra puertas donde antes había muros.',
  'Una idea pequeña puede abrir posibilidades inmensas.',
  'La inspiración aparece cuando confías en tu visión.',
  'Cada creación habla desde la esencia.',
  'Un corazón libre invita a nuevas historias.',
  'La imaginación transforma lo cotidiano en extraordinario.',
  'Nuevas ideas se revelan cuando te das permiso de explorar.',
  'La creatividad se nutre de tus preguntas.',
  'Un destello interior puede cambiarlo todo.',
  'La curiosidad convierte cualquier rincón en un universo.',
  'Cada paso creativo amplía tus horizontes.',
  'La inspiración puede nacer de lo más simple.',
  'Crear también es una forma de celebrar la vida.',
  'La fuerza interior crece cuando reconoces tu propio ritmo.',
  'Un paso sereno también es señal de fortaleza.',
  'La calma frente a lo incierto revela tu poder.',
  'En cada avance discreto hay valentía.',
  'Sostener tu propio camino demuestra grandeza.',
  'La fortaleza también vive en los corazones sensibles.',
  'Tu esencia mantiene firme lo que construyes.',
  'Cada reto superado te confirma lo lejos que puedes llegar.',
  'La estabilidad nace de confiar en lo que te sostiene.',
  'Mantenerte presente es un acto de entereza.',
  'La fuerza auténtica no siempre se nota; se siente.',
  'Seguir, incluso despacio, habla de tu coraje.',
  'Hay grandeza en respetar tus límites.',
  'Un corazón que insiste demuestra su brillantez.',
  'La resiliencia florece cuando eliges continuar.',
  'Caminar con firmeza honra tu historia.',
  'En cada aprendizaje hay nueva fortaleza.',
  'Lo que te nutre por dentro refuerza tu paso.',
  'La paciencia también construye poder.',
  'Una mente estable inspira caminos luminosos.',
  'Tu presencia frente a los desafíos ya es valentía.',
  'La fuerza se manifiesta cuando cuidas de ti.',
  'Cada día trae una nueva oportunidad para fortalecerte.',
  'La confianza interior sostiene tus decisiones.',
  'Quien mantiene la fe en su rumbo se vuelve más fuerte.',
  'El espíritu se afianza cuando sigues tu verdad.',
  'La serenidad al elegir es signo de carácter.',
  'Lo que te sostiene en silencio también es poder.',
  'Una mirada firme puede cambiar el destino.',
  'La verdadera fortaleza honra tanto la acción como el descanso.',
  'El amor da sentido a lo que tocas y a lo que sueñas.',
  'Un acto amoroso puede convertir lo cotidiano en algo especial.',
  'Cada gesto de cariño deja huellas invisibles.',
  'El amor crece cuando se comparte con sinceridad.',
  'La ternura suaviza cualquier distancia.',
  'Donde hay comprensión, el amor encuentra su hogar.',
  'Un corazón abierto irradia paz sin decir palabra.',
  'El afecto se multiplica cuando lo das sin reservas.',
  'La cercanía se nutre de atención y de escucha.',
  'Amar también es permitir que la otra persona sea libre.',
  'La compasión revela la profundidad del amor verdadero.',
  'Cada muestra de bondad amplía los horizontes del alma.',
  'El amor auténtico no exige; acompaña.',
  'Un pensamiento amoroso puede cambiar el rumbo de un día.',
  'La empatía es una de las formas más puras del amor.',
  'Amar la vida es agradecerla en cada detalle.',
  'El amor también se expresa en la paciencia.',
  'Cada vínculo cuidado con amor florece a su tiempo.',
  'La presencia amorosa es el mejor refugio.',
  'El amor inspira, sostiene y renueva la esperanza.',
  'Un corazón amoroso siempre encuentra caminos de paz.',
  'Amar lo que haces enciende la pasión por vivir.',
  'El amor transforma lo ordinario en algo significativo.',
  'Un acto de bondad puede ser la semilla de algo eterno.',
  'El amor sin palabras también se siente.',
  'Amar es reconocer la belleza en lo que existe.',
  'Cada expresión de cariño alimenta la conexión humana.',
  'El amor genuino da fuerza incluso en el silencio.',
  'Un alma amorosa deja luz donde pasa.',
  'Amar sin miedo abre paso a la libertad interior.',
  'El amor siempre encuentra la forma de seguir presente.',
];

export const PAINFUL_PHRASES: string[] = [
  'Luego de respirar con calma, algo puede cambiar.',
  'Si hoy el camino se siente complicado, no tienes que resolver todo ahora. Avanzar paso a paso también es avanzar.',
  'Hay momentos en los que todo parece más difícil. Con paciencia, muchas situaciones encuentran su lugar.',
  'Puede que hoy el ánimo esté bajo. Recuerda que ningún estado interior permanece para siempre.',
  'Cuando el día pesa más de lo habitual, detenerse un momento puede ayudarte a recuperar perspectiva.',
  'Tal vez hoy el panorama parece confuso. Con tiempo y calma, muchas cosas comienzan a aclararse.',
  'Hay días en los que simplemente necesitamos respirar más profundo. Desde ahí pueden surgir nuevas fuerzas.',
  'Si hoy todo parece cuesta arriba, recuerda que incluso los pasos pequeños cuentan.',
  'Puede que hoy te cueste ver una salida clara. Sin embargo, tu proceso continúa avanzando.',
  'Cuando el interior se siente inquieto, una pausa puede ayudarte a recuperar equilibrio.',
  'Es natural tener días complicados. Lo importante es seguir avanzando con paciencia.',
  'Tal vez hoy sientes que algo pesa. Recuerda que este momento no define todo tu camino.',
  'Hay momentos en los que la mente se llena de preocupaciones. Con calma, muchas de ellas pierden fuerza.',
  'Si hoy el día se siente difícil, trátate con comprensión. La pausa también es parte del progreso.',
  'Puede que hoy necesites más paciencia contigo. Ese gesto también es una forma de cuidado.',
  'Cuando las cosas parecen desordenadas, el tiempo suele ayudar a reorganizar.',
  'Si hoy el panorama parece incierto, recuerda que muchas respuestas aparecen con el tiempo.',
  'Aun cuando el camino parezca difícil, cada paso cuenta.',
  'Cuando el interior se siente cansado, darte un momento de calma puede ayudar mucho.',
  'Si te das un tiempo para observarte, notarás que dentro de ti existe la capacidad de sanar.',
  'Tal vez hoy te cuesta encontrar claridad. Con paciencia, las cosas pueden comenzar a ordenarse.',
  'Cuando la vida parece exigir demasiado, poco a poco el equilibrio vuelve.',
  'Si hoy algo parece complicado, recuerda que no necesitas resolverlo todo hoy.',
  'Puede que hoy sientas que el camino se volvió pesado. Avanzar con suavidad también es avanzar.',
  'Cuando el ánimo baja, es normal sentir malestar. Con calma, el rumbo puede aclararse.',
  'Tal vez hoy algo no fluye como esperabas. Mañana puede verse diferente.',
  'Hay días en que algo de la vida parece detenerse. Sin embargo, los procesos interiores siguen avanzando.',
  'Si hoy te cuesta avanzar, recuerda que descansar forma parte del camino.',
  'Puede que hoy el ánimo esté cansado. Con tiempo, la energía vuelve a renovarse.',
  'En días nublados, una pausa puede ayudarte a recuperar perspectiva.',
  'Aunque hoy se vean algunas nubes, recuerda que ningún momento es permanente.',
  'Hay momentos en los que el interior necesita silencio. Desde ahí muchas cosas comienzan a aclararse.',
  'Si encuentras una piedra en el camino, avanza con calma. Incluso los pasos pequeños tienen valor.',
  'La claridad siempre vuelve después de la oscuridad.',
  'Cuando el ánimo se debilita, tratarte con amabilidad puede marcar una gran diferencia.',
  'Tal vez un obstáculo complique el camino. Con paciencia, el rumbo vuelve a abrirse.',
  'Hay días en los que el simple hecho de continuar ya es una forma de fortaleza.',
  'Si hoy el interior se siente inquieto, respirar con calma puede ayudarte a recuperar equilibrio.',
  'Puede que hoy algo parezca nublar el panorama. Con tiempo, muchas situaciones encuentran sentido.',
  'Tal vez hoy el día se siente más pesado de lo habitual. Permítete ir paso a paso.',
  'Hay momentos en los que necesitamos mayor autocomprensión.',
  'Si hoy el ánimo no acompaña, recuerda que las etapas cambian.',
  'Puede que hoy el día se sienta complicado. Sin embargo, cada momento también puede traer aprendizaje.',
  'Cuando todo parece incierto, la paciencia se vuelve una gran aliada.',
  'Tal vez hoy algo parezca complicado. Aun así, este momento no define todo tu camino.',
  'Si te tomas un momento para respirar, te darás cuenta de que, con calma, muchas cosas comienzan a aclararse.',
  'No todos los momentos se sienten iguales. Incluso las situaciones difíciles pueden convertirse en oportunidades para comprender algo nuevo.',
  'Puede que te sientas sin mucha energía en algunos momentos. Con paciencia, incluso los instantes pesados terminan cambiando.',
  'Cuando el ánimo baja, es natural sentirse más vulnerable. Trátate con amabilidad mientras recuperas equilibrio.',
  'Tal vez hoy te cueste encontrar claridad en algunos espacios de tu vida. Con el tiempo, muchas situaciones terminan acomodándose.',
  'Hay días en los que el corazón necesita más calma que respuestas. Esa pausa también forma parte del camino.',
  'Si hoy ciertos instantes del día se sienten pesados, recuerda que cada proceso tiene su ritmo.',
  'Puede que algunas cosas no se sientan bien. Aun así, dentro de ti existe la capacidad de reorganizar lo que estás viviendo.',
  'Cuando todo parece complicado, avanzar poco a poco puede ayudarte a recuperar dirección.',
  'Es normal que haya momentos difíciles. Lo importante es recordar que también pueden transformarse.',
  'Cuando hay agitación interior, respirar con calma puede devolver perspectiva.',
  'Puede que sientas que algunas cosas se salieron de control. Poco a poco es posible volver a ordenarlas.',
  'Hay momentos en los que necesitamos bajar el ritmo. Desde ahí muchas cosas comienzan a acomodarse.',
  'Si hoy algo en el día no se siente bien, date permiso de avanzar con suavidad.',
  'Tal vez sientes que un momento pesa más. Recuerda que este momento también pasará.',
  'Cuando el ánimo está bajo, incluso los pequeños avances tienen un gran valor.',
  'Puede que en el camino afrontes una situación difícil. Sin embargo, incluso los procesos complejos traen aprendizaje.',
  'Si sientes cansancio, recuerda que descansar también forma parte del proceso.',
  'Tal vez el panorama no luzca como quisieras. Con el tiempo, muchas cosas encuentran sentido.',
  'Puede que hoy el día parezca más largo de lo habitual. Aun así, cada momento también pasa.',
  'Si ahora el ánimo no acompaña, trátate con paciencia mientras recuperas fuerza.',
  'Tal vez haya topes en el camino. Incluso así, avanzar despacio sigue siendo avanzar.',
  'En momentos de confusión o dolor, darte un momento de pausa puede ayudarte a ordenar tus pensamientos.',
  'Puede que la motivación no aparezca con facilidad, pero a veces basta un pequeño cambio de enfoque para encontrarla.',
  'Si en el panorama se presenta una complicación, recuerda que no necesitas resolverlo todo al mismo tiempo.',
  'Si hoy sientes que falta una dirección clara, respirar con calma y tomar una pausa puede mostrarte el camino.',
  'Tal vez en este momento te cuesta encontrar tranquilidad. Es algo que muchas personas experimentan. Poco a poco el equilibrio puede volver.',
  'Recuerda que incluso los momentos difíciles también cambian.',
  'Puede que el ánimo no esté como quisieras. Eso también forma parte de la experiencia humana. Con paciencia, nuevas fuerzas aparecen.',
  'Hay instantes que parecen más complicados. Incluso así, avanzar con suavidad puede ayudarte a recuperar claridad.',
  'Tal vez tu interior se siente inquieto ahora. Es natural que ocurra en algunos momentos. Con calma, muchas cosas vuelven a ordenarse.',
  'Si en el camino hay un contratiempo, cada pequeño paso sigue teniendo valor.',
  'Si sientes cansancio por dentro, recuerda que, con descanso y paciencia, la energía vuelve.',
  'Incluso en esos instantes abrumadores, es posible empezar a recuperar equilibrio.',
  'Tal vez hoy el día no fluye como esperabas. Es algo que le ocurre a muchas personas. Con el tiempo, nuevas perspectivas aparecen.',
  'Puede que hoy el ánimo se sienta frágil. Eso también forma parte de la experiencia humana. Tratarte con amabilidad puede ayudarte mucho.',
  'Aun cuando el panorama parezca complicado, con paciencia, muchas situaciones comienzan a aclararse.',
  'Puede que hoy sientas que algo pesa más de la cuenta. Es una sensación humana común. Con calma, ese peso puede disminuir.',
  'Aun cuando el camino se sienta pedregoso, avanzar con suavidad también es progreso.',
  'En momentos en los que algo parece demasiado, muchas situaciones terminan aclarando su sentido.',
  'Cuando hay inquietud atrapada en el interior, respirar con calma puede ayudarte a liberarla.',
  'Si hoy el panorama no luce claro, recuerda que, con el tiempo, las nubes se van y muchas cosas se acomodan.',
  'En momentos de incertidumbre, la paciencia trae muchas respuestas.',
  'Si una nube te cubre, recuerda que pasará y este momento no define todo tu camino.',
  'Si hoy el interior se siente saturado, una pausa puede ayudarte a recuperar perspectiva y despejar tu mundo interno.',
  'Si el ánimo no está como quisieras, las cosas pueden mejorar con paciencia.',
  'Si hoy el día se siente pesado, recuerda que los estados emocionales también cambian.',
  'Cuando el interior se siente cansado, escucharte con paciencia puede ayudarte a recuperar claridad.',
  'Puede que hoy el camino parezca largo. Sin embargo, cada paso te acerca a un lugar distinto.',
  'Hay momentos en los que es necesario confiar en que las cosas pueden mejorar.',
  'Cuando el día se siente difícil, avanzar con suavidad puede marcar una gran diferencia.',
  'Puede que hoy te cueste ver algo positivo. Con el tiempo, nuevas perspectivas aparecen.',
  'Si hoy el interior se siente inquieto, date un momento para respirar. Desde ahí muchas cosas pueden empezar a ordenarse.',
  'Tal vez hoy el panorama parece complicado. Con calma, nuevas posibilidades pueden aparecer.',
  'Puede que hoy te sientas más sensible de lo habitual. Eso también forma parte de la experiencia humana.',
  'Cuando el interior se siente confundido, una pausa puede ayudarte a recuperar perspectiva.',
  'Si sientes inquietud, recuerda que los procesos personales también necesitan tiempo.',
  'Cuando enfrentas complicaciones, avanzar con suavidad puede ayudarte a recuperar equilibrio.',
  'Tal vez hoy el camino se ve largo. Incluso así, cada paso sigue siendo importante.',
  'Puede que hoy sientas que todo se volvió más difícil. Aun así, este momento no define todo tu camino.',
  'Hay días en los que es necesario simplemente seguir adelante con calma.',
  'Tal vez hoy el interior se siente saturado. Una pausa puede ayudarte a recuperar claridad.',
  'Puede que hoy el día no fluya como quisieras. Mañana puede traer nuevas posibilidades.',
  'Hay momentos en los que la vida pide paciencia antes de mostrar dirección.',
  'Cuando el ánimo se debilita, recordar que todo cambia puede ayudarte a seguir adelante.',
  'Hay momentos en los que es necesario confiar en nuestro propio proceso.',
  'Si hoy el día se siente difícil, trátate con comprensión mientras avanzas poco a poco.',
  'Tal vez hoy el interior se siente inquieto. Con calma, muchas cosas comienzan a aclararse.',
  'Cuando todo parece confuso, respirar y esperar un poco puede ayudar a recuperar perspectiva.',
  'Si hoy te cuesta avanzar como quisieras, permítete hacerlo a tu propio ritmo.',
  'Si en el día algo se dificulta, recuerda que cada momento también puede traer aprendizaje.',
  'Si hay inquietud en el interior, recuerda que esa sensación también puede ser el inicio de una transformación positiva.',
  'Si hoy te cuesta confiar en que las cosas mejorarán, recuerda que, con el tiempo, muchas situaciones encuentran su equilibrio.',
  'Tal vez hoy el interior se siente inquieto y frágil. Tratarte con amabilidad puede ayudarte a atravesar este momento.',
  'En momentos en los que todo parece desbordarse, respirar con calma puede ayudarte a recuperar equilibrio.',
  'En momentos en los que el camino parece más difícil de lo habitual, cada paso hacia adelante cuenta.',
  'Si hoy te cuesta encontrar esperanza, obsérvate: nuevas posibilidades siguen existiendo.',
  'Hay días en los que simplemente es necesario atravesarlos con paciencia.',
  'Puede que hoy te cueste encontrar serenidad. Si observas tu vida, te darás cuenta de que, con el tiempo, muchas emociones vuelven a su lugar.',
  'Cuando la mente se llena de pensamientos, recuerda que, con calma, muchos de ellos pierden intensidad.',
  'Si hoy el panorama no parece grato, recuerda que la claridad suele regresar.',
  'Puede que hoy te cueste encontrar dirección. Con calma, muchas rutas aparecen.',
  'Recuerda que incluso los días difíciles pueden convertirse en el inicio de algo nuevo.',
  'A veces sentir que algo te supera no significa debilidad; significa que algo dentro de ti necesita atención y cuidado.',
  'No todo malestar necesita resolverse de inmediato; a veces primero necesita ser escuchado.',
  'Si hoy te sientes más sensible, no te exijas dureza; trátate como tratarías a alguien importante para ti.',
  'Hay momentos en los que sostenerte con suavidad vale más que exigirte respuestas rápidas.',
  'A veces el cansancio emocional no pide fuerza, sino descanso, comprensión y un poco de silencio.',
  'Si hoy algo duele por dentro, recuerda que reconocerlo ya es una forma de empezar a cuidarte.',
  'No necesitas sentirte bien de inmediato para seguir en tu camino; a veces basta con no abandonarte.',
  'Hay días en los que el mayor acto de fortaleza consiste en tratarte con mayor comprensión.',
  'Si hoy sientes demasiada carga, date permiso de atender sólo lo esencial. Eso también es sabiduría.',
  'A veces una emoción intensa no viene a destruirte, sino a mostrarte que algo importante necesita de tu atención.',
  'Si hoy no puedes con todo, recuerda que nadie está bien todos los días y eso también es profundamente humano.',
  'Hay momentos en los que bajar la exigencia interior abre más espacio que seguir presionándote.',
  'Si hoy te cuesta sostener el ritmo, quizá tu interior te está pidiendo una forma más amable de continuar.',
  'No siempre necesitas encontrar explicación inmediata a lo que sientes; a veces basta con darte un poco de compañía interior.',
  'Incluso cuando el ánimo cae, tu valor personal permanece intacto.',
  'Si hoy te sientes distante de ti, vuelve a lo simple: respirar, sentir tu cuerpo y darte un momento real.',
  'Hay días en los que mirar con honestidad lo que sientes ya es un paso importante hacia el alivio.',
  'Si hoy algo en tu interior no se siente bien, no concluyas demasiado pronto; muchas partes de ti también saben reconstruirse.',
  'A veces el corazón necesita menos juicio y más espacio para acomodar lo vivido.',
  'Si hoy te pesa lo que estás cargando, recuerda que no todo tiene que resolverse en una sola jornada.',
  'Hay momentos en los que permitirte sentir cansancio también es una forma de respeto hacia ti.',
  'Si hoy sientes que no estás en tu centro, vuelve a lo pequeño: una respiración, una pausa, un paso.',
  'No todo avance se nota por fuera; a veces avanzar también es no rendirte contigo.',
  'Si hoy el malestar está presente, intenta no pelearte con él de inmediato; primero obsérvalo con calma.',
  'Hay días en los que sentir confusión no es un error, sino una etapa antes de una nueva claridad.',
  'Si hoy te cuesta encontrarte bien, recuerda que los procesos internos también necesitan tiempo para acomodarse.',
  'A veces lo más compasivo no es empujarte, sino acompañarte con más paciencia.',
  'Si hoy sientes que ya no puedes más, reduce el día a un paso posible y empieza por ahí.',
  'Hay momentos en los que una pequeña muestra de ternura hacia ti puede cambiar la forma en que atraviesas el día.',
  'Si hoy la mente insiste demasiado, regresar al cuerpo puede ayudarte: respirar, aflojar hombros, bajar el ritmo.',
  'A veces el interior no necesita respuestas brillantes; necesita un poco de calma para dejar de doler tanto.',
  'Hay días en los que no sentirte bien no significa que estés mal en tu proceso; significa que estás viviendo algo real.',
  'Si hoy el peso emocional parece excesivo, recuerda que pedirte menos también puede ser una forma de equilibrio.',
  'A veces el primer alivio aparece cuando dejas de exigirte estar bien todo el tiempo.',
  'Si hoy te cuesta mirar hacia adelante, concéntrate sólo en cuidar este momento. Lo demás puede esperar un poco.',
  'Hay momentos en los que tu tarea principal no es resolver la vida, sino atravesar el día con dignidad.',
  'Si hoy te sientes vulnerable, recuerda que la vulnerabilidad también puede ser un puente hacia una comprensión más profunda.',
  'Si hoy te pesa lo que nadie ve, honra también ese esfuerzo silencioso que estás haciendo por seguir.',
  'Hay días en los que el simple hecho de seguir buscándote por dentro ya es una forma de esperanza.',
];
