export const StackNav = {
  Splash: 'Splash',
  OnBoarding: 'OnBoarding',
  ThankYou: 'ThankYou',
  AuthNavigation: 'AuthNavigation',
  TabNavigation: 'TabNavigation',
  DoctorDetail: 'DoctorDetail',
  Appointment: 'Appointment',
  BookAppointment: 'BookAppointment',
  WaitingRoom: 'WaitingRoom',
  Chat: 'Chat',
  VideoCall: 'VideoCall',
  Notification: 'Notification',
  MyAddress: 'MyAddress',
  AddNewAddress: 'AddNewAddress',
  MyPayment: 'MyPayment',
  AddNewCard: 'AddNewCard',
  HelpAndSupport: 'HelpAndSupport',
  Configuration: 'Configuration',
  Languages: 'Languages',
  FormsStack: 'FormsStack',
  Subscription: 'Subscription',
  WelcomeEmotion: 'WelcomeEmotion',
  SessionsMenu: 'SessionsMenu',
  TasksMenu: 'TasksMenu',
  EvaluationsMenu: 'EvaluationsMenu',
  WorkedRecommendations: 'WorkedRecommendations',
  WorkedExercises: 'WorkedExercises',
  WellnessNetwork: 'WellnessNetwork',
  TestsGabo: 'TestsGabo',
  TestDetail: 'TestDetail',
  TestResult: 'TestResult',
  TestResultsHistory: 'TestResultsHistory',
  Profile: 'Profile',
  ApoyoFinanciero: 'ApoyoFinanciero',
  ApoyoAceptado: 'ApoyoAceptado',
};

export const AuthNav = {
  Welcome: 'Welcome',
  Login: 'Login',
  Register: 'Register',
  ForgotPassword: 'ForgotPassword',
  OtpScreen: 'OtpScreen',
  CreateNewPassword: 'CreateNewPassword',
};

export const TabNav = {
  HomeTab: 'HomeTab',
  CalenderTab: 'CalenderTab',
  EvaluationsTab: 'EvaluationsTab',
  TestsTab: 'TestsTab',
};
